# ==================================================
# Plugin: SDAntiCraft
# Author: ShaneDev
# Version: 1.0
# Support Discord: https://discord.gg/Z6eF4QP4gD
# ==================================================


#Prefix of the plugin in chat
Prefix: "&f&lAntiCraft &8&l» "

#Message to send when a player tries crafting a blocked item
Blocked-Message: '&c&lThis recipe is blocked!'

#Blocked Recipes
Blocked-Recipes:
  - MATERIAL
